<?php declare(strict_types=1);
//Copyright (c) 2022 ReCodem Pvt Ltd All rights reserved
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->getCollection()->getSize()) :?>
    <?php $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
    $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
    ?>
    <div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>
        <?php if ($block->getIsBottom()): ?>


        <?php else: ?>
            <?php if ($block->isExpanded()): ?>

            <?php endif ?>

            <?php if ($block->isExpanded()): ?>

            <?php endif ?>
        <?php endif ?>
    </div>
<?php endif ?>
